# Generated by Django 2.2.5 on 2019-12-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaxoristis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='money',
            field=models.FloatField(),
        ),
    ]
